### ISSUE TITLE
[PE-D] Functionality Bug - E-mail format not accepted

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103-W16-1/tp#123]
![image.png](https://raw.githubusercontent.com/Harish-coding/ped/main/files/44a55c5f-ce91-4db4-b038-2b172f2f507c.png)

![image.png](https://raw.githubusercontent.com/Harish-coding/ped/main/files/9cea7b29-5ece-4b03-9f2f-1c53ec8fa6d1.png)

Functionality Bug:
When the following example from the User Guide is copy - pasted to the command box of the app, an error message is displayed showing that e-mail format is not correct.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: Harish-coding/ped#3

**Comment by yokester98** [comment]
Error is in the wrong prefix being used here. Hence, the email is read as `aarontan@gmail.com a/COM2`, which is indeed an invalid email format.

Previously our office tag was `a/` instead of `of/`. Will edit the typo in User Guide.
