### ISSUE TITLE
[PE-D] Disguitish persons bug

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103-W16-1/tp#143]
Students with similar names can be put, how to distinguish person 4 and 5

![image.png](https://raw.githubusercontent.com/thikhinab/ped/main/files/d0664c40-aa36-4e31-9efa-c860f15b4ca4.png)

-------------
Labels: `severity.High` `type.FeatureFlaw`
original: thikhinab/ped#8

**Comment by benmurphyy** [comment]
This is by design, as people can have the same name, similar to regular contact apps, in a case like this it is up to the user to know the difference based on the other fields
