### ISSUE TITLE
[PE-D] Wrong error message for adding a module

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103-W16-1/tp#146]
I tried adding a new module with this command like in the image below, however, it displayed an error message that datetime field is missing even though it is not.
![image.png](https://raw.githubusercontent.com/flairekq/ped/main/files/7f585398-9219-41f3-93db-3c01d5887db6.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: flairekq/ped#7

**Comment by yokester98** [comment]
Fixed.
